services:
  # Order App
  order-app:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./order-service:/var/www
    depends_on:
      - order-db
    networks:
      - order-pipeline

  order-nginx:
    image: nginx:alpine
    container_name: order-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./order-service:/var/www
      - ./order-service/docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - order-app
    networks:
      - order-pipeline

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    restart: unless-stopped
    environment:
      DB_HOST: order-db
      DB_PORT: 5432
      POSTGRES_DB: order_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./.docker/order-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - order-pipeline

  # Shipping App
  shipping-app:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    container_name: shipping-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./shipping-service:/var/www
    depends_on:
      - shipping-db
    networks:
      - order-pipeline

  shipping-nginx:
    image: nginx:alpine
    container_name: shipping-nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./shipping-service:/var/www
      - ./shipping-service/docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - shipping-app
    networks:
      - order-pipeline

  shipping-db:
    image: postgres:16-alpine
    container_name: shipping-db
    restart: unless-stopped
    environment:
      DB_HOST: shipping-db
      DB_PORT: 5432
      POSTGRES_DB: shipping_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./.docker/shipping-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"    
    networks:
      - order-pipeline

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - order-pipeline

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    networks:
      - order-pipeline

networks:
  order-pipeline:
    driver: bridge